### ISSUE TITLE
Doesn't compile on Ubuntu or Windows 10

### ISSUE THREAD

**Issue by VincePlatt** [vascokk/fullstack-rust#2]
I'm not sure if I'm doing something wrong, but the build doesn't recognize yew-services as a dependency.

>~/rust/fullstack-rust$ cargo build
    Updating crates.io index
    Updating git repository `https://github.com/yewstack/yew.git`
error: no matching package named `yew-services` found
location searched: https://github.com/yewstack/yew.git?branch=master
required by package `client v0.1.0 (/home/azureuser/rust/fullstack-rust/client)`

>~/rust/fullstack-rust$ rustc --version
rustc 1.54.0 (a178d0322 2021-07-26)

Should I be using an older version of rust or is there something else I can do to resolve it?  

Obviously, it's not critical as I was just interested in your example, but I would try any suggestions you might have and get back to you.  Thanks!

**Comment by vascokk** [comment]
Hi @VincePlatt. The project was using Yew from the master branch. Since the Yew team is constantly introducing breaking changes (in fairness, they warn you about it), at some point this stopped working. I set the Yew version to release 0.18. This should fix the problem (tested on macOS).
Also, yew-services is now part of the main yew crate (i.e. yew::services).
